'use strict';
// Versioned research tasks and driver models use the same local API and evidence drawer.
Object.assign(names,{research:'研究任务台',drivers:'经营驱动模型',extraction:'提取与审核'});
const researchLabels={independent_disclosures:'独立披露值数值一致',derived_consistency:'仅计算自洽',unverified_lineage:'来源依赖未确认',unresolved:'尚未通过'};
const driverLabels={volume_growth:'销量指数年增长 %',price_growth:'净价格指数年变化 %',unit_cost_growth:'单位成本指数年变化 %',retention:'原有客户留存 %',expansion:'留存客户收入扩张 %',new_customer_rate:'新增客户相对期初 %',new_customer_timing:'新增客户当年确认比例（0—1）',service_cost_growth:'服务成本年增长 %',opex_growth:'净经营费用年增长 %',tax_rate:'现金税率 %',da_ratio:'折旧摊销 / 收入 %',capex_ratio:'资本开支 / 收入 %',dso:'应收周转天数假设',dio:'存货周转天数假设',dpo:'应付周转天数假设',opening_nwc:'期初应收＋存货－应付 / 百万'};
let driverResult=null,driverPayload=null;const driverDrafts={},researchDrafts={};let researchRequest=0;
const inputField=(name,title,value='',type='text')=>`<label>${esc(title)}<input name="${name}" type="${type}" ${type==='number'?'step="any"':''} value="${esc(value)}" required></label>`;
const textField=(name,title,value='')=>`<label class="wide">${esc(title)}<textarea name="${name}" rows="3" required>${esc(value)}</textarea></label>`;
const sourceOptions=(docs=state.documents)=>docs.map(d=>`<option value="${esc(d.id)}">${esc(d.title)} · ${esc(d.disclosed_at)}</option>`).join('');
const sourceField=()=>`<label class="wide">关联依据（不代表资料支持全部假设）<select name="source_id" required><option value="">选择当前研究时点的资料</option>${sourceOptions()}</select></label>`;
const versionCards=(kind)=>records(kind).map(r=>`<article class="record">${recordHeader(r)}<p>${esc(r.content.reason||r.content.question||r.content.observation||r.content.provider||r.content.draft_id||'已保存版本')}</p><button class="text-button" data-record="${esc(r.id)}">查看完整依据与输入</button>${kind==='driver'?`<button class="secondary" data-revise-driver="${r.id}">基于此版本修改</button>`:''}${kind==='research'?`<button class="secondary" data-revise-research="${r.id}">修订这条判断</button>`:''}</article>`).join('')||empty('尚无保存记录。');

const renderBeforeResearch=render;
render=function(){
 if(!state)return;
 const ticket=++researchRequest;
 if(!['research','drivers','extraction'].includes(page)){renderBeforeResearch();if(page==='overview')$('#content').insertAdjacentHTML('afterbegin','<section class="task-guide"><div><h2>从一个研究问题开始</h2><p>选任务、核证据、建立经营假设，再留下可修订的判断。</p></div><button class="primary" data-go="research">开始研究任务 →</button></section>');return;}
 $('#breadcrumb').textContent=names[page];$('#errorBox').hidden=true;$$('nav button').forEach(b=>b.setAttribute('aria-current',b.dataset.page===page?'page':'false'));
 if(page==='research')researchView();
 if(page==='drivers')driverView(ticket).catch(fail);
 if(page==='extraction')extractionView();
};

const beforeRelations=relationsView;
relationsView=function(){
 beforeRelations();
 $('#ruleList').insertAdjacentHTML('beforebegin',`<p class="note">独立披露值一致 ${state.relations.coverage.independent_disclosures} 项；仅计算自洽 ${state.relations.coverage.derived_consistency} 项。数值检查与人工审核是不同状态。</p>`);
 $$('.rule-item').forEach((el,i)=>{const c=state.relations.checks[i];el.querySelector('summary .badge').textContent=c.status==='pass'?researchLabels[c.verification]:statusName[c.status];el.querySelector('.rule-body').insertAdjacentHTML('afterbegin',`<p><b>${esc(researchLabels[c.verification])}</b> · ${c.reviewed?'所需指标均已人工确认':'仍有待人工确认的指标'}</p>${c.derived_inputs.length?`<p class="note">衍生输入：${c.derived_inputs.map(k=>esc(labels[k])).join('、')}。不能以推导结果反向证明原数据正确。</p>`:''}${c.dependent_inputs.length?'<p class="note">检测到输入由本规则内其他指标推导，不能作为独立交叉核验。</p>':''}`)});
};

function researchView(){
 const formKey=key();
 const tasks=[['cash','利润增长是否转化为现金？','先核对利润与现金流，再解释资金占用。','relations'],['competition','竞争优势是否体现在经营结果中？','先确认竞争范围，再比较财务差异和其他解释。','compare'],['growth','增长来自量、价还是客户结构？','用经营驱动拆解假设，观察利润与资金需求。','drivers']];
 $('#content').innerHTML=`<section class="paper">${head('今天要回答什么问题？','每次围绕一个问题完成研究；资料不足时保留待验证结论。')}<div class="research-tasks">${tasks.map(([id,title,note,target])=>`<button class="task-card" data-task="${id}" data-target="${target}"><b>${title}</b><span>${note}</span><small>选择任务并查看下一步 →</small></button>`).join('')}</div><div id="taskSteps"></div></section><section class="paper">${head('留下可被推翻的判断','保存初始判断；新证据到来后，选择历史版本修订。真实保存时间始终保留。')}<form id="researchForm" class="form-grid">${textField('question','研究问题',state.company.question)}${textField('conclusion','当前判断与支持依据')}${textField('alternative','其他解释 / 反证')}${textField('next_evidence','下一项要找的证据与推翻条件')}${textField('change_reason','建立或修改判断的理由')}${sourceField()}<label>当前状态<select name="status"><option value="open">待验证</option><option value="supported">当前证据支持</option><option value="challenged">遭到反证挑战</option><option value="withdrawn">已撤回</option></select></label><label>关联经营模型<select name="model_id"><option value="">暂不关联</option>${records('driver').map(r=>`<option value="${r.id}">${esc(r.created_at)} · ${esc(r.content.reason.slice(0,45))}</option>`).join('')}</select></label><input type="hidden" name="parent_id" value=""><div class="wide action-row"><button class="primary">保存研究判断</button><span id="researchEditStatus">新判断</span></div></form></section><section class="paper">${head('判断如何变化','版本不会覆盖；可展开查看旧依据。')}${versionCards('research')}</section>`;
 const researchForm=$('#researchForm');const remember=()=>researchDrafts[formKey]=Object.fromEntries(new FormData(researchForm));researchForm.oninput=remember;if(researchDrafts[formKey])for(const [k,v] of Object.entries(researchDrafts[formKey]))if(researchForm.elements[k])researchForm.elements[k].value=v;
 $$('[data-task]').forEach(b=>b.onclick=()=>{const t=tasks.find(x=>x[0]===b.dataset.task);$('#researchForm [name="question"]').value=t[1];remember();$('#taskSteps').innerHTML=`<ol class="task-steps"><li>检查当前 ${state.observations.length} 条来源指标，待审核 ${state.review_pending} 条。</li><li>${t[2]}</li><li>记录依据、其他解释与推翻条件；保存一个判断版本。</li></ol><button class="primary" data-go="${t[3]}">开始第一步 →</button>`;});
 $('#researchForm').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));try{await api('research-save',{...p,source_ids:[p.source_id]});delete researchDrafts[formKey];toast('研究判断已保存，后续可基于此版本修订');await load()}catch(err){fail(err)}};
 $$('[data-revise-research]').forEach(b=>b.onclick=()=>{const r=records('research').find(r=>r.id===b.dataset.reviseResearch);const f=$('#researchForm');for(const [k,v] of Object.entries(r.content))if(f.elements[k]&&typeof v==='string')f.elements[k].value=v;f.elements.source_id.value=r.content.source_ids[0];f.elements.parent_id.value=r.id;f.elements.change_reason.value='';$('#researchEditStatus').textContent='正在修订 '+r.created_at;remember();f.scrollIntoView({behavior:'smooth'})});
}

async function driverView(ticket){
 $('#content').innerHTML=empty('正在读取可用的经营基数…');const response=await api('driver-defaults',{});if(ticket!==researchRequest)return;
 if(!response.suggested){$('#content').innerHTML=empty('当前缺少收入、成本、毛利或经营利润，或属于金融机构。请先补充可用资料。')+'<button class="primary" data-go="evidence">查看数据与来源</button>';return;}
 const draft=driverDrafts[key()]||{...response.suggested,reason:'',counter:'',trigger:'',source_id:'',parent_id:''};driverResult=null;
 $('#content').innerHTML=`<section class="paper">${head('把经营机制传导到利润与现金','全部参数均为研究假设。基期 100 的量价指数不是披露销量；订阅运行率不是公司披露 ARR。')}<form id="driverForm" class="form-grid"><label class="wide">经营结构<select name="template"><option value="hardware">硬件：量 × 价，成本随量与单位成本变化</option><option value="software">订阅：留存 × 扩张 ＋ 新增客户</option></select></label><div id="driverFields" class="form-grid wide"></div>${textField('reason','这些经营假设依据是什么？',draft.reason)}${textField('counter','反证或其他解释',draft.counter)}${textField('trigger','什么结果会让你修改假设？',draft.trigger)}${sourceField()}<input type="hidden" name="parent_id" value="${esc(draft.parent_id)}"><div class="wide action-row"><button class="primary" type="submit">计算经营传导</button><button class="secondary" id="saveDriver" type="button">计算并保存版本</button><button class="text-button" id="fillDriverExample" type="button">填入明确标注的练习依据</button></div><p id="driverDirty" class="note wide">${esc(response.suggested.note)}</p></form></section><section id="driverOutput"></section><section class="paper">${head('经营版本与改动','修改旧版本时保留参数差异及结果变化。')}<div id="driverVersions">${versionCards('driver')}</div></section>`;
 const f=$('#driverForm');f.elements.template.value=draft.template;f.elements.source_id.value=draft.source_id;
 const paint=values=>{const common=['opex_growth','tax_rate','da_ratio','capex_ratio','dso','dio','dpo','opening_nwc'];const fields=items=>items.map(([k,v])=>inputField(k,driverLabels[k],v,'number')).join('');$('#driverFields').innerHTML=fields(Object.entries(values).filter(([k])=>!common.includes(k)))+'<details class="wide"><summary>资金占用、费用与税：展开核对假设</summary><div class="form-grid">'+fields(Object.entries(values).filter(([k])=>common.includes(k)))+'</div></details>'};paint(draft.params);
 const read=()=>{const data=Object.fromEntries(new FormData(f));const params={};$$('#driverFields input').forEach(n=>params[n.name]=Number(n.value));return {template:data.template,params,reason:data.reason,counter:data.counter,trigger:data.trigger,source_ids:[data.source_id],source_id:data.source_id,parent_id:data.parent_id||null}};
 const dirty=()=>{driverDrafts[key()]=read();driverResult=null;$('#driverDirty').textContent='有未计算的编辑。已显示的结果仍属于上次计算。'};
 f.oninput=dirty;
 f.elements.template.onchange=()=>{const common=Object.fromEntries(Object.entries(read().params).filter(([k])=>!['volume_growth','price_growth','unit_cost_growth','retention','expansion','new_customer_rate','new_customer_timing','service_cost_growth'].includes(k)));paint({...common,...(f.elements.template.value==='hardware'?{volume_growth:10,price_growth:0,unit_cost_growth:0}:{retention:95,expansion:5,new_customer_rate:10,new_customer_timing:.5,service_cost_growth:5})});f.elements.parent_id.value='';dirty()};
 const run=async save=>{if(!f.reportValidity())return;try{const requestKey=key();driverPayload=read();const p=await api(save?'driver-save':'driver-calculate',driverPayload);if(requestKey!==key()||page!=='drivers')return;driverResult=save?p.result:p;driverOutput(driverResult);$('#driverDirty').textContent=save?'当前版本已保存。':'已计算，尚未冻结版本。';if(save){delete driverDrafts[key()];toast('经营模型版本已保存');const next=await api('state?'+new URLSearchParams(context()));if(requestKey!==key()||page!=='drivers')return;state=next;$('#driverVersions').innerHTML=versionCards('driver');bindDriverRevisions();}}catch(e){fail(e)}};
 f.onsubmit=e=>{e.preventDefault();run(false)};$('#saveDriver').onclick=()=>run(true);
 $('#fillDriverExample').onclick=()=>{f.elements.reason.value='练习假设：以当前披露收入与成本为基数，测试所填经营参数；暂无证据证明这些增长率会实现。';f.elements.counter.value='竞争、产品组合或合同确认节奏可能改变，不能把比例假设当作事实。';f.elements.trigger.value='后续同口径收入、利润或资金占用偏离模型时，重新核验机制并保存修订。';if(state.documents.length)f.elements.source_id.value=state.documents[0].id;dirty()};
 bindDriverRevisions();
}

function bindDriverRevisions(){$$('[data-revise-driver]').forEach(b=>b.onclick=()=>{const r=records('driver').find(r=>r.id===b.dataset.reviseDriver);driverDrafts[key()]={...r.content,source_id:r.content.source_ids[0],parent_id:r.id,reason:''};render()});}

function driverOutput(result){
 const keys=['revenue','cost','gross_profit','net_opex','ebit','cash_tax','receivables','inventory','payables','delta_nwc','da','capex','fcff'];const titles={...labels,net_opex:'净经营费用',ebit:'经营利润',cash_tax:'假设现金税',delta_nwc:'增量资金占用',fcff:'FCFF / 自由现金流'};
 $('#driverOutput').innerHTML=`<div class="paper">${head('五年经营传导表',result.currency+' million · Assumed + Calculated')}<div class="table-wrap"><table><thead><tr><th>指标</th>${result.rows.map(r=>`<th>${esc(r.year)}</th>`).join('')}</tr></thead><tbody>${keys.map(k=>`<tr><th>${esc(titles[k])}</th>${result.rows.map(r=>`<td>${fmt(r[k],2)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="note">收入 → 成本与费用 → 税后经营利润 → 折旧、资本开支、资金占用 → FCFF。这里只是部分经营与资金联动，不是完整三表。</p></div><div class="paper">${head('收入变化由哪些假设贡献？','量价交互归入价格效应；订阅新增收入按当年确认比例计入。')}<div class="table-wrap"><table><thead><tr><th>年度</th><th>期初收入</th><th>假设效应</th><th>期末收入</th></tr></thead><tbody>${result.bridges.map(b=>`<tr><th>${esc(b.year)}</th><td>${fmt(b.opening_revenue,2)}</td><td>${b.effects.map(x=>esc(x.name)+' '+fmt(x.value,2)).join('<br>')}</td><td>${fmt(b.closing_revenue,2)}</td></tr>`).join('')}</tbody></table></div>${result.change?`<h3>相对父版本的改动</h3><ul>${result.change.params.map(p=>`<li>${esc(driverLabels[p.parameter])}: ${p.before} → ${p.after}</li>`).join('')}</ul><p>首年收入变化 ${fmt(result.change.rows[0].revenue,2)}；首年 FCFF 变化 ${fmt(result.change.rows[0].fcff,2)}。</p>`:''}<details><summary>查看假设与适用限制</summary>${result.warnings.map(w=>`<p>${esc(w)}</p>`).join('')}</details></div>`;
}

const originalPeerResults=peerResults;
peerResults=function(result){
 originalPeerResults(result);const rows=result.rows;const table=$$('#peerResults table')[1];const keys=['revenue','gross_profit','operating_income','net_income','cfo','receivables','inventory','sbc','gross_margin','op_margin','cash_conversion','sbc_ratio'];
 [...table.tBodies[0].rows].forEach((tr,i)=>rows.forEach((r,j)=>{const check=r.metric_checks[keys[i]],cell=tr.cells[j+1];cell.replaceChildren();if(check.status==='blocked'){cell.textContent='不可比';cell.title=check.reasons.join('；')}else{const b=document.createElement('button');b.className='link-button';b.textContent=fmt(check.value,2)+(i>=8?'%':'')+' ↗';b.onclick=()=>drawer(r.name+' / '+(labels[keys[i]]||keys[i]),`<p>${esc(b.textContent)} · ${i>=8?'比率':esc(r.currency)+' million'}</p><p>${esc(check.notes.join('；'))}</p><div class="table-wrap"><table><thead><tr><th>本期输入</th><th>数值</th><th>来源</th></tr></thead><tbody>${r.observations.filter(o=>i>=8||o.metric===keys[i]).map(o=>{const d=r.documents.find(d=>d.id===o.source_id);return `<tr><td>${esc(labels[o.metric]||o.metric)}</td><td>${fmt(o.value,2)}</td><td>${d?`<a href="${esc(d.url)}" target="_blank" rel="noopener noreferrer">${esc(d.locator)}</a>`:'缺失'}</td></tr>`}).join('')}</tbody></table></div>`);cell.append(b)}}));
 $('#peerResults').insertAdjacentHTML('beforeend',`<section class="paper">${head('冻结这次比较','保存当前输入与限制；同行更新时提示重新核验。')}<form id="comparisonSave" class="action-row"><input name="reason" required aria-label="比较结论" placeholder="这次比较说明什么，又不能说明什么？"><button class="primary">保存比较快照</button></form>${versionCards('comparison')}</section><section class="paper">${head('业务层与产品层的竞争解释','这是你的研究判断，需要两方来源；不自动生成竞争力评分。')}<form id="businessForm" class="form-grid"><label>比较层级<select name="level"><option value="company">公司</option><option value="segment">业务分部</option><option value="product">产品 / 客户场景</option></select></label><label>竞争对象<select name="peer">${rows.filter(r=>r.ticker!==context().company).map(r=>`<option value="${r.ticker}">${esc(r.name)}</option>`).join('')}</select></label>${inputField('subject','具体业务 / 产品 / 客户场景')}${inputField('dimension','比较维度（如部署成本、渠道、收入结构）')}${textField('observation','观察到的差异')}${textField('mechanism','为什么可能影响客户选择与财务表现？')}${textField('alternative','其他解释 / 反证')}${textField('trigger','哪些新证据会改变判断？')}${sourceField()}<label class="wide">对方来源<select name="peer_source_id" required></select></label><div class="wide"><button class="primary">保存有证据的竞争判断</button></div></form>${versionCards('business-note')}</section>`);
 $('#comparisonSave').onsubmit=async e=>{e.preventDefault();await perform('comparison-save',{peers:rows.slice(1).map(r=>r.ticker),nearby:result.nearby,reason:new FormData(e.target).get('reason')},'比较快照已保存')};
 const f=$('#businessForm');const update=()=>f.elements.peer_source_id.innerHTML=sourceOptions(rows.find(r=>r.ticker===f.elements.peer.value)?.documents||[]);f.elements.peer.onchange=update;update();f.onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(f));await perform('business-note',{...p,source_ids:[p.source_id],peer_source_ids:[p.peer_source_id]},'竞争判断已保存；这是解释，尚非因果证明')};
};

function extractionView(){
 $('#content').innerHTML=`<section class="paper">${head('让每次提取留下审核记录','本地规则可离线运行；也可粘贴外部 AI 候选 JSON。本项目不会把资料发送到外部模型。')}<form id="extractionForm" class="form-grid">${sourceField()}${inputField('period','财政期间','FY2024')}${inputField('period_start','期间开始','','date')}${inputField('period_end','期间结束','','date')}<label>原文单位<select name="unit"><option value="million">百万</option><option value="one">元 / 基础单位</option><option value="thousand">千</option><option value="ten_thousand">万</option><option value="billion">十亿</option></select></label><label class="wide">提取方式<select name="provider"><option value="local-rules">本地规则：单行指标与数值</option><option value="external-json">导入外部 AI 候选（本项目未调用模型）</option></select></label>${textField('text','粘贴原文片段；每行“指标名：数值”，歧义行会留空')}<details class="wide"><summary>外部候选 JSON 格式</summary><p>每条需包含 metric、value、quote；quote 必须存在于本次原文中。不要粘贴密钥。示例：[{"metric":"revenue","value":100,"quote":"营业收入：100"}]</p><textarea name="external" rows="4" aria-label="外部候选 JSON">[]</textarea></details><button class="primary wide">生成候选草稿，不写入财务表</button></form></section><section id="candidateReview"></section><section class="paper">${head('审核历史','接受率只是操作记录，不是独立真值准确率。')}${records('extraction').map(r=>`<article class="record">${recordHeader(r)}<p>${esc(r.content.provider)} · ${r.content.candidates.length} 条候选</p><button class="secondary" data-open-extraction="${r.id}">继续审核草稿</button></article>`).join('')}${versionCards('extraction-review')}<div class="action-row">${records('extraction-review').map(r=>`<button class="secondary" data-import-review="${r.id}">导入已审核版本 ${esc(r.created_at)}</button>`).join('')}</div></section>`;
 $('#extractionForm').onsubmit=async e=>{e.preventDefault();try{const p=Object.fromEntries(new FormData(e.target));if(p.provider==='external-json')p.external=JSON.parse(p.external);const r=await api('extraction-draft',p);showCandidates(r.id,r.result);toast('草稿已保存；尚未进入正式财务数据')}catch(e){fail(e)}};
 $$('[data-import-review]').forEach(b=>b.onclick=async()=>{try{await api('extraction-import',{id:b.dataset.importReview});page='evidence';await load();toast('已审核候选已导入')}catch(e){fail(e)}});
 $$('[data-open-extraction]').forEach(b=>b.onclick=()=>{const r=records('extraction').find(r=>r.id===b.dataset.openExtraction);showCandidates(r.id,r.content)});
}
function showCandidates(id,draft){
 $('#candidateReview').innerHTML=`<div class="paper">${head('逐条审核候选','接受、修正或拒绝；每条都记录原因。随后另行确认导入。')}<form id="candidateForm"><div class="table-wrap"><table><thead><tr><th>原文</th><th>指标代码</th><th>金额</th><th>决定</th><th>原因</th></tr></thead><tbody>${draft.candidates.map((r,i)=>`<tr data-candidate="${i}"><td>${esc(r.quote)}</td><td><input name="metric${i}" value="${esc(r.metric)}" required aria-label="候选指标 ${i+1}"></td><td><input name="value${i}" type="number" step="any" value="${r.value}" required aria-label="候选金额 ${i+1}"></td><td><select name="action${i}" aria-label="审核决定 ${i+1}"><option value="accept">接受原候选</option><option value="correct">采用修正值</option><option value="reject">拒绝</option></select></td><td><input name="reason${i}" required placeholder="为何这样处理" aria-label="审核原因 ${i+1}"></td></tr>`).join('')}</tbody></table></div><p class="note">${draft.unmatched.length} 行未提取，未自动猜测。</p><details><summary>查看未识别内容</summary>${draft.unmatched.map(x=>`<p>${esc(x.text)} — ${esc(x.reason)}</p>`).join('')}</details><button class="primary" ${draft.candidates.length?'':'disabled'}>保存审核决定</button></form><div id="candidateSummary"></div></div>`;
 $('#candidateForm').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);const decisions=draft.candidates.map((r,i)=>{const metric=f.get('metric'+i),value=Number(f.get('value'+i)),action=f.get('action'+i);if(action==='accept'&&(metric!==r.metric||value!==r.value))throw Error('已编辑指标或金额，请选择“采用修正值”');return {action,metric,value,reason:f.get('reason'+i)}});const result=await api('extraction-review',{id,decisions});const ev=result.result.evaluation;$('#candidateSummary').innerHTML=`<p>已记录：接受 ${ev.accept}，修正 ${ev.correct}，拒绝 ${ev.reject}。财务表尚未改变。</p><button id="importAccepted" class="primary">将已接受结果校验并导入财务表</button>`;$('#importAccepted').onclick=async()=>{try{await api('extraction-import',{id:result.id});toast('已导入。候选审核与财务核验分别保留');page='evidence';await load()}catch(e){fail(e)}}}catch(e){fail(e)}};
 $('#candidateReview').scrollIntoView({behavior:'smooth'});
}

$('nav').insertAdjacentHTML('afterbegin','<button data-page="research"><span>00</span>研究任务台</button>');
$('nav [data-page="model"]').insertAdjacentHTML('beforebegin','<button data-page="drivers"><span>+</span>经营驱动模型</button>');
$('nav [data-page="evidence"]').insertAdjacentHTML('beforebegin','<button data-page="extraction"><span>+</span>提取与审核</button>');
$$('nav button').forEach((b,i)=>b.querySelector('span').textContent=String(i+1).padStart(2,'0'));
